/**
 * Regenerate iopex-presenter/agent/knowledge-base.md from BOTH surfaces.
 *
 *     node agent/build-kb.mjs
 *
 * The presenter agent spans two surfaces: the iOPEX products page (the index of
 * the pitch) and the DigiAura architecture deck. Both are the source of truth for
 * what the client can actually see, so the knowledge base is generated rather
 * than written — an agent quoting a capability the deck no longer renders is the
 * failure mode this avoids.
 *
 * data.js imports icon components it never needs here, so the imports are
 * stubbed before evaluating it rather than installing anything.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = dirname(HERE);
const DATA_JS = '/Users/sudarmathim/digiaura-presentation/src/data.js';
const PRODUCTS_HTML = join(ROOT, 'index.html');
const OUT = join(HERE, 'knowledge-base.md');

/** Evaluate data.js with its icon imports replaced by harmless stubs. */
async function loadDeckData(path) {
  const src = await readFile(path, 'utf8');
  const importRe = /import\s*\{([^}]+)\}\s*from\s*['"][^'"]+['"];?/g;

  const names = new Set();
  let m;
  while ((m = importRe.exec(src)) !== null) {
    for (const part of m[1].split(',')) {
      const name = part.trim().split(/\s+as\s+/).pop().trim();
      if (name) names.add(name);
    }
  }

  const stubs = [...names].map((n) => `const ${n} = null;`).join('\n');
  const body = src.replace(importRe, '');
  const mod = `${stubs}\n${body}`;
  return import(`data:text/javascript;base64,${Buffer.from(mod).toString('base64')}`);
}

/** Pull the visible copy out of the products page, section by section. */
async function loadProductsCopy(path) {
  let html = await readFile(path, 'utf8');
  html = html.slice(html.indexOf('<body'));
  html = html.replace(/<(script|style|svg)\b[\s\S]*?<\/\1>/gi, '');

  const sections = [];
  // Split on section boundaries so each block of copy stays attributable to the
  // anchor the agent would scroll to.
  const parts = html.split(/<section\b([^>]*)>/i);
  for (let i = 1; i < parts.length; i += 2) {
    const attrs = parts[i];
    const id = (attrs.match(/id="([^"]+)"/) || [])[1];
    const cls = (attrs.match(/class="([^"]+)"/) || [])[1];
    const text = parts[i + 1]
      .replace(/<[^>]+>/g, ' ')
      .replace(/&nbsp;/g, ' ')
      .replace(/&amp;/g, '&')
      .replace(/&rsquo;|&#8217;/g, "'")
      .replace(/&mdash;/g, '—')
      .replace(/&ndash;/g, '–')
      .replace(/\s+/g, ' ')
      .trim();
    if (text) sections.push({ anchor: id || cls, text });
  }
  return sections;
}

// The tool argument the agent passes maps onto a section, not the raw anchor.
const SECTION_TOOL_NAME = {
  hero: 'hero', products: 'products', 'dv-intro': 'digivox', 'dv-why': 'why',
  'dv-setup': 'setup', 'dv-voices': 'voices', 'dv-scoring': 'scoring',
  'dv-platform': 'platform', 'dv-results': 'results', 'dv-cta': 'cta',
};

const out = [];
const w = (s = '') => out.push(s);

const data = await loadDeckData(DATA_JS);
const copy = await loadProductsCopy(PRODUCTS_HTML);

w('# iOPEX Presenter — Knowledge Base');
w();
w('Generated by `agent/build-kb.mjs` — do not edit by hand.');
w();
w('The presenter works across two surfaces. The `{{deck}}` variable says which one');
w('the client is looking at:');
w();
w('| `{{deck}}` | Surface | Tools that work there |');
w('| --- | --- | --- |');
w('| `products` | iOPEX products page — the index of the pitch | `goToSection`, `setInterviewerPersona`, `tuneVoice`, `openArchitecture`, `getPageContext` |');
w('| `architecture` | DigiAura living architecture deck | `playStory`, `nextStep`, `previousStep`, `goToStep`, `stopStory`, `switchScreen`, `openCapability`, `backToOverview`, `switchSquad`, `quoteMetrics`, `getDeckContext` |');
w();
w('Calling a tool that belongs to the other surface returns guidance instead of');
w('acting. Move the client with `openArchitecture` first.');

/* ─────────────────────────── products page ─────────────────────────── */

w();
w('---');
w();
w('## Surface 1 — iOPEX products page');
w();
w('The company: iOPEX Technologies, founded 2009, 3,000+ specialists worldwide,');
w('serving Fortune 500 clients. Three products — **DigiVox** (AI interview and');
w('proctoring, live today), **DigiAura** (enterprise agentic AI platform, in');
w('build, has its own architecture deck) and **DigiCoach** (coming soon, no');
w('detail to share yet).');
w();
w('### Sections, and the `goToSection` value for each');
w();
w('| Say this to `goToSection` | What the client sees |');
w('| --- | --- |');
for (const { anchor, text } of copy) {
  const name = SECTION_TOOL_NAME[anchor];
  if (!name) continue;
  const summary = text.length > 220 ? text.slice(0, 217) + '…' : text;
  w(`| \`${name}\` | ${summary.replace(/\|/g, '\\|')} |`);
}

w();
w('### DigiVox interviewer personas');
w();
w('`setInterviewerPersona` accepts these. Switching one moves all four tuner');
w('sliders, which the client sees happen.');
w();
w('| Persona | Character | Empathy · Exploration · Rapport · Speed |');
w('| --- | --- | --- |');
w('| `monika` | Warm and thorough, Indian accent | 0.9 · 0.7 · 0.7 · 0.5 |');
w('| `akash` | Listens for depth and connection, Indian accent | 1.0 · 0.7 · 0.7 · 0.5 |');
w('| `ryan` | Direct and structured, US accent | 0.6 · 0.9 · 0.5 · 0.7 |');
w('| `jane` | Calm and encouraging, US accent | 0.85 · 0.6 · 0.8 · 0.4 |');
w();
w('`tuneVoice` takes any of `empathy`, `exploration`, `rapport`, `speed` as 0–1.');
w('Every persona runs the same evaluation logic underneath — the tone is what');
w('changes, and that is the point worth making.');

/* ───────────────────────── architecture deck ───────────────────────── */

const { DOMAINS, ARCH_DEMO, SUPPORT_DEMO, SQUADS, METRICS } = data;

w();
w('---');
w();
w('## Surface 2 — DigiAura living architecture');
w();
w('Two screens, switched with `switchScreen`: `architecture` (the capability map)');
w('and `support` (the app-support squad in motion).');

w();
w('### The architecture story — 8 steps');
w();
w('`playStory` starts at step 1; `nextStep` advances. Each step centres a');
w('capability group and hands you the line below to narrate **in your own words**.');
w('Never read a caption verbatim — they are written to be read, not heard.');
w();
for (const [i, s] of ARCH_DEMO.entries()) {
  w(`${i + 1}. **${s.node}** — ${s.caption}`);
}

w();
w('### The app-support story — 9 steps');
w();
for (const [i, s] of SUPPORT_DEMO.entries()) {
  w(`${i + 1}. **${s.node}** — ${s.caption}`);
}

w();
w('### Capability groups');
w();
w('`openCapability` expands one in place on the architecture screen. Use the id.');
w();
for (const d of DOMAINS) {
  w(`#### \`${d.id}\` — ${d.title}`);
  w();
  w(`*${d.tag}*`);
  w();
  w(d.blurb);
  w();
  for (const [, label, desc] of d.children) {
    w(`- **${label}** — ${desc}`);
  }
  w();
}

w('### Squad variants');
w();
w('`switchSquad` on the support screen:');
w();
for (const s of SQUADS) {
  const note = s.drop ? ` (no ${s.drop.join(', ')} tier)` : s.rename
    ? ` (${Object.entries(s.rename).map(([k, v]) => `${k} renamed ${v}`).join(', ')})` : '';
  w(`- \`${s.id}\` — ${s.title}${note}`);
}

w();
w('### The numbers');
w();
w('`quoteMetrics` switches to the support screen and returns these. Quote at most');
w('two in a breath — a list of four read aloud lands as noise.');
w();
w('| Measure | Before | After |');
w('| --- | --- | --- |');
for (const m of METRICS) {
  w(`| ${m.label} | ${m.fmt(m.before)} | ${m.fmt(m.after)} |`);
}

/* ───────────────────────────── guardrails ──────────────────────────── */

w();
w('---');
w();
w('## Never do these');
w();
w('- Never read a step caption or a blurb word for word. Narrate it.');
w('- Never quote a number that is not in the table above.');
w('- Never claim DigiAura or DigiCoach is generally available. DigiVox is live; DigiAura is in build; DigiCoach has no detail to share.');
w('- Never invent a customer name, a logo, a price, a delivery date or a contract term.');
w('- Never name or compare a competitor.');
w('- Never describe a capability group that is not in this document, even if it sounds plausible for a platform like this.');
w('- Never promise an integration, a certification or a security control that is not listed in a group above.');
w('- If asked something you do not have, say so in one sentence and offer to take it away — a presenter who says "I will get you that" outperforms one who guesses.');

await writeFile(OUT, out.join('\n') + '\n');
console.error(`wrote ${OUT}`);
console.error(
  `${DOMAINS.length} capability groups, ${ARCH_DEMO.length + SUPPORT_DEMO.length} story steps, ` +
  `${copy.length} page sections, ${METRICS.length} metrics`
);
